base_url = "https://seniormars.github.io/redux/"
title = "seniormars"
description = "This is an example description"
build_search_index = false
feed_filenames = ["rss.xml"]
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
favicon_extra = false
theme = "toggle"              # light, dark, auto, toggle
comment = false
fancy_code = true
dynamic_note = true
repo_url = "https://github.com/SeniorMars/seniormars.com/blob/main/content/"
mathjax = true
mathjax_extra = true

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
    { name = "/tags", url = "/tags", weight = 4 },
]

# keep for now
socials = [
    { name = "github", url = "https://github.com/seniormars/", icon = "github" },
    { name = "youtube", url = "https://www.youtube.com/seniormarstries", icon = "youtube" },
    { name = "rss", url = "/rss.xml", icon = "rss" },
]

custom_css = []

[extra.analytics]
enabled = false

[extra.analytics.goatcounter]
user = "your_user"
host = "example.com" # default= goatcounter.com

[extra.analytics.umami]
website_id = "43929cd1-1e83...."
host_url = "https://stats.mywebsite.com" # default: https://analytics.eu.umami.is
